# generated by appcreator
from django.contrib import admin
from . models import (
    Bibliothek,
    Initium,
    Manuscript,
    MsDesc,
    MsPart,
    Place,
    Verfasser
)
admin.site.register(Bibliothek)
admin.site.register(Initium)
admin.site.register(Manuscript)
admin.site.register(MsDesc)
admin.site.register(MsPart)
admin.site.register(Place)
admin.site.register(Verfasser)
