# generated by appcreator
from django.contrib import admin
from . models import (
    Autor,
    Bibliothek,
    Initium,
    Literatur,
    Manuscript,
    MsDesc,
    MsPart,
    Place,
    Verfasser,
    WerkInstanz
)
admin.site.register(Autor)
admin.site.register(Bibliothek)
admin.site.register(Initium)
admin.site.register(Literatur)
admin.site.register(Manuscript)
admin.site.register(MsDesc)
admin.site.register(MsPart)
admin.site.register(Place)
admin.site.register(Verfasser)
admin.site.register(WerkInstanz)
