# generated by appcreator
from django.urls import path
from . import dal_views

app_name = "archiv"
urlpatterns = [
    path("autor-autocomplete/", dal_views.AutorAC.as_view(), name="autor-autocomplete"),
    path(
        "bibliothek-autocomplete/",
        dal_views.BibliothekAC.as_view(),
        name="bibliothek-autocomplete",
    ),
    path(
        "initium-autocomplete/",
        dal_views.InitiumAC.as_view(),
        name="initium-autocomplete",
    ),
    path(
        "literatur-autocomplete/",
        dal_views.LiteraturAC.as_view(),
        name="literatur-autocomplete",
    ),
    path(
        "manuscript-autocomplete/",
        dal_views.ManuscriptAC.as_view(),
        name="manuscript-autocomplete",
    ),
    path(
        "msdesc-autocomplete/",
        dal_views.MsDescAC.as_view(),
        name="msdesc-autocomplete",
    ),
    path(
        "mspart-autocomplete/",
        dal_views.MsPartAC.as_view(),
        name="mspart-autocomplete",
    ),
    path("place-autocomplete/", dal_views.PlaceAC.as_view(), name="place-autocomplete"),
    path(
        "verfasser-autocomplete/",
        dal_views.VerfasserAC.as_view(),
        name="verfasser-autocomplete",
    ),
    path(
        "weblit-autocomplete/",
        dal_views.WebLitAC.as_view(),
        name="weblit-autocomplete",
    ),
    path(
        "werkinstanz-autocomplete/",
        dal_views.WerkInstanzAC.as_view(),
        name="werkinstanz-autocomplete",
    ),
    path("zitat-autocomplete/", dal_views.ZitatAC.as_view(), name="zitat-autocomplete"),
]
