# generated by appcreator
from django.db.models import Q
from dal import autocomplete
from . models import *


class ManuscriptAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Manuscript.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(ms_code__icontains=self.q)
            )
        return qs


