# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^manuscript-autocomplete/$',
        dal_views.ManuscriptAC.as_view(),
        name='manuscript-autocomplete'
    ),
]
