# generated by appcreator
import django_tables2 as tables

from browsing.browsing_utils import MergeColumn
from .models import (
    Autor,
    Bibliothek,
    Initium,
    Literatur,
    Manuscript,
    MsDesc,
    MsPart,
    Place,
    Verfasser,
    WebLit,
    WerkInstanz,
    Zitat,
    Einband,
    Schrift,
    MsImage,
    Person,
)


class AutorTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Autor
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class BibliothekTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Bibliothek
        sequence = (
            "id",
            "lib_name",
        )
        attrs = {"class": "table table-responsive table-hover"}


class InitiumTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Initium
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class LiteraturTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Literatur
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class ManuscriptTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Manuscript
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class MsDescTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = MsDesc
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class MsPartTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = MsPart
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PlaceTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Place
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class VerfasserTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Verfasser
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class WebLitTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = WebLit
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class WerkInstanzTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = WerkInstanz
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class ZitatTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Zitat
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class EinbandTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Einband
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class SchriftTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Schrift
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class MsImageTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = MsImage
        sequence = ("id",)
        attrs = {"class": "table table-responsive table-hover"}


class PersonTable(tables.Table):

    id = tables.LinkColumn(verbose_name="ID")
    merge = MergeColumn(verbose_name="keep | remove", accessor="pk")

    class Meta:
        model = Person
        sequence = ("id", "name",)
        attrs = {"class": "table table-responsive table-hover"}