# generated by appcreator
from django.conf.urls import url
from . import views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^manuscript/$',
        views.ManuscriptListView.as_view(),
        name='manuscript_browse'
    ),
    url(
        r'^manuscript/detail/(?P<pk>[0-9]+)$',
        views.ManuscriptDetailView.as_view(),
        name='manuscript_detail'
    ),
    url(
        r'^manuscript/create/$',
        views.ManuscriptCreate.as_view(),
        name='manuscript_create'
    ),
    url(
        r'^manuscript/edit/(?P<pk>[0-9]+)$',
        views.ManuscriptUpdate.as_view(),
        name='manuscript_edit'
    ),
    url(
        r'^manuscript/delete/(?P<pk>[0-9]+)$',
        views.ManuscriptDelete.as_view(),
        name='manuscript_delete'),
]
