# generated by appcreator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from . filters import *
from . forms import *
from . tables import *
from . models import (
    Manuscript
)
from browsing.browsing_utils import (
    GenericListView, BaseCreateView, BaseUpdateView, BaseDetailView
)


class ManuscriptListView(GenericListView):

    model = Manuscript
    filter_class = ManuscriptListFilter
    formhelper_class = ManuscriptFilterFormHelper
    table_class = ManuscriptTable
    init_columns = [
        'id', 'ms_code',
    ]
    enable_merge = True


class ManuscriptDetailView(BaseDetailView):

    model = Manuscript
    template_name = 'browsing/generic_detail.html'


class ManuscriptCreate(BaseCreateView):

    model = Manuscript
    form_class = ManuscriptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ManuscriptCreate, self).dispatch(*args, **kwargs)


class ManuscriptUpdate(BaseUpdateView):

    model = Manuscript
    form_class = ManuscriptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ManuscriptUpdate, self).dispatch(*args, **kwargs)


class ManuscriptDelete(DeleteView):
    model = Manuscript
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('archiv:manuscript_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ManuscriptDelete, self).dispatch(*args, **kwargs)


