# Generated by Django 5.1.1 on 2024-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="indentifier",
            field=models.URLField(
                blank=True,
                default="http://www.vocabs/manuscripta-django/",
                help_text="URI",
            ),
        ),
        migrations.AlterField(
            model_name="skoscollection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skosconcept",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skosconceptscheme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skoslabel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skosnamespace",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="skosnamespace",
            name="namespace",
            field=models.URLField(
                blank=True, default="http://www.vocabs/manuscripta-django/"
            ),
        ),
        migrations.AlterField(
            model_name="skosnamespace",
            name="prefix",
            field=models.CharField(
                blank=True, default="manuscripta-django", max_length=50
            ),
        ),
    ]
