# Generated by Django 3.1.1 on 2020-10-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('ms_code', models.CharField(blank=True, help_text='MS-Code', max_length=250, verbose_name='MS-Code')),
                ('ms_code_sort', models.CharField(blank=True, help_text='MS-Code (Sortierung)', max_length=250, verbose_name='MS-Code (Sortierung)')),
                ('shelfmark', models.CharField(blank=True, help_text='Signatur', max_length=250, verbose_name='Signatur')),
                ('heading', models.TextField(blank=True, help_text='Heading', null=True, verbose_name='Heading')),
                ('num_leaves', models.CharField(blank=True, help_text='Umfang (Anzahl der Blätter)', max_length=250, verbose_name='Umfang')),
                ('dimensions', models.CharField(blank=True, help_text='Dimensionen', max_length=250, verbose_name='Dimensionen')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('material', models.ForeignKey(blank=True, help_text='Material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_manuscript_material_skosconcept', to='vocabs.skosconcept', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Manuscript',
                'ordering': ['ms_code_sort'],
            },
        ),
    ]
