# Generated by Django 3.1.1 on 2020-10-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('lib_code', models.CharField(blank=True, help_text='Bibliothekscode', max_length=250, verbose_name='Bibliothekscode')),
                ('lib_name', models.CharField(blank=True, help_text='Name', max_length=250, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, help_text='Name (Abkürzung)', max_length=250, verbose_name='Name (Abkürzung)')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('lib_type', models.ForeignKey(blank=True, help_text='Art der Bibliothek', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_bibliothek_lib_type_skosconcept', to='vocabs.skosconcept', verbose_name='Art der Bibliothek')),
            ],
            options={
                'verbose_name': 'Bibliothek',
                'ordering': ['lib_name'],
            },
        ),
    ]
