# Generated by Django 3.1.1 on 2020-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_bibliothek'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='fragm',
            field=models.CharField(blank=True, help_text='Fragm', max_length=250, verbose_name='Fragm'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='geschichte',
            field=models.TextField(blank=True, help_text='Geschcihte', null=True, verbose_name='Geschichte'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='hscensus',
            field=models.IntegerField(blank=True, help_text='hscensus', null=True, verbose_name='hscensus'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='origin_date',
            field=models.CharField(blank=True, help_text='Entstehungsdatum', max_length=250, verbose_name='Entstehungsdatum'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='prov',
            field=models.TextField(blank=True, help_text='Provenienz', null=True, verbose_name='Provenienz'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='remarks',
            field=models.TextField(blank=True, help_text='Anmerkungen', null=True, verbose_name='Anmerkungen'),
        ),
    ]
