# Generated by Django 3.1.1 on 2020-10-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_auto_20201023_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='lib_code',
            field=models.ForeignKey(blank=True, help_text='Bibliothek', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_manuscript_lib_code_bibliothek', to='archiv.bibliothek', verbose_name='Bibliothek'),
        ),
    ]
