# Generated by Django 3.1.1 on 2020-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0003_weblit_zitat"),
    ]

    operations = [
        migrations.AddField(
            model_name="initium",
            name="signtaur_fol",
            field=models.CharField(
                blank=True,
                help_text="Signatur (Folio)",
                max_length=250,
                verbose_name="Signatur (Folio)",
            ),
        ),
        migrations.AddField(
            model_name="initium",
            name="titel",
            field=models.CharField(
                blank=True, help_text="Titel", max_length=250, verbose_name="Titel"
            ),
        ),
        migrations.AddField(
            model_name="initium",
            name="titel_vorspann",
            field=models.CharField(
                blank=True,
                help_text="Titelvorspann",
                max_length=250,
                verbose_name="Titelvorspann",
            ),
        ),
    ]
