# Generated by Django 3.1.1 on 2020-10-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_manuscript_lib_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('name', models.CharField(blank=True, help_text='Ortsname', max_length=250, verbose_name='Ortsname')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
            ],
            options={
                'verbose_name': 'Place',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bibliothek',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='geschichte',
            field=models.TextField(blank=True, help_text='Geschichte', null=True, verbose_name='Geschichte'),
        ),
        migrations.AddField(
            model_name='bibliothek',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Ort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_bibliothek_location_place', to='archiv.place', verbose_name='Ort'),
        ),
    ]
