# Generated by Django 3.1.1 on 2020-10-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_auto_20201023_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('range', models.CharField(blank=True, help_text='von-bis', max_length=250, verbose_name='von-bis')),
                ('date_str', models.CharField(blank=True, help_text='datum', max_length=250, verbose_name='datum')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('part_of_manuscript', models.ForeignKey(blank=True, help_text='Teil von Handschrift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_mspart_part_of_manuscript_manuscript', to='archiv.manuscript', verbose_name='Teil von Handschrift')),
            ],
            options={
                'verbose_name': 'MsPart',
                'ordering': ['legacy_pk'],
            },
        ),
    ]
