# Generated by Django 5.1.1 on 2024-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0005_auto_20201026_1144"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initium",
            options={"ordering": ["manuscript", "fol_sort"], "verbose_name": "Initium"},
        ),
        migrations.AddField(
            model_name="manuscript",
            name="adest",
            field=models.IntegerField(
                blank=True, help_text="adest", null=True, verbose_name="adest"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="date",
            field=models.CharField(
                blank=True, help_text="date", max_length=250, verbose_name="date"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="ISO-Date nicht nach (JJJJ-MM-TT)",
                null=True,
                verbose_name="Datierung (nicht nach)",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="folio_range",
            field=models.CharField(
                blank=True, help_text="range", max_length=250, verbose_name="range"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="ms_group",
            field=models.IntegerField(
                blank=True, help_text="ms_group", null=True, verbose_name="ms_group"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="olim_signatur",
            field=models.CharField(
                blank=True, help_text="Olim", max_length=250, verbose_name="Olim"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="origin",
            field=models.CharField(
                blank=True, help_text="origin", max_length=250, verbose_name="origin"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="ISO-Date nicht vor (JJJJ-MM-TT)",
                null=True,
                verbose_name="Datierung (nicht vor)",
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bibliothek",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="initium",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="literatur",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="fragm",
            field=models.CharField(
                blank=True, help_text="Fragmente", max_length=250, verbose_name="Fragm"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="msdesc",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mspart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="verfasser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="weblit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="werkinstanz",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="zitat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
