# Generated by Django 3.1.1 on 2020-10-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_mspart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspart',
            name='date_being',
            field=models.DateField(blank=True, help_text='Datum (start, norm)', null=True, verbose_name='Datum (start, norm)'),
        ),
        migrations.AddField(
            model_name='mspart',
            name='date_end',
            field=models.DateField(blank=True, help_text='Datum (end, norm)', null=True, verbose_name='Datum (end, norm)'),
        ),
        migrations.AddField(
            model_name='mspart',
            name='origin_date',
            field=models.CharField(blank=True, help_text='Datum (orig)', max_length=250, verbose_name='Datum (orig)'),
        ),
        migrations.AlterField(
            model_name='mspart',
            name='date_str',
            field=models.CharField(blank=True, help_text='Datum (str)', max_length=250, verbose_name='Datum (str)'),
        ),
        migrations.CreateModel(
            name='Initium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('initium', models.TextField(blank=True, help_text='Initium', null=True, verbose_name='Inititum')),
                ('explicit', models.TextField(blank=True, help_text='Explicit', null=True, verbose_name='Explicit')),
                ('fol', models.CharField(blank=True, help_text='Folio', max_length=250, verbose_name='Folio')),
                ('fol_sort', models.CharField(blank=True, help_text='Folio (sort)', max_length=250, verbose_name='Folio (sort)')),
                ('fol_end', models.CharField(blank=True, help_text='Folio (end)', max_length=250, verbose_name='Folio (end)')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('manuscript', models.ForeignKey(blank=True, help_text='Manuscript', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_initium_manuscript_manuscript', to='archiv.manuscript', verbose_name='Manuscript')),
            ],
            options={
                'verbose_name': 'Initium',
                'ordering': ['legacy_pk'],
            },
        ),
    ]
