# Generated by Django 5.1.1 on 2024-09-25 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0006_alter_initium_options_manuscript_adest_and_more"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="bibliography",
            field=models.TextField(
                blank=True,
                help_text="Bibliographie",
                null=True,
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="jahrhundert",
            field=models.CharField(
                blank=True,
                help_text="Jahrhundert (in standardisierter Schreibweise)",
                null=True,
                verbose_name="Jahrhundert",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="orden",
            field=models.ForeignKey(
                blank=True,
                help_text="Mitglied eines Ordens",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_autor_orden_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Orden",
            ),
        ),
    ]
