# Generated by Django 3.1.1 on 2020-10-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_auto_20201023_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mspart',
            old_name='date_being',
            new_name='date_begin',
        ),
    ]
