# Generated by Django 5.1.1 on 2024-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0007_autor_bibliography_autor_jahrhundert_autor_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliothek",
            name="hbhistbb",
            field=models.URLField(
                blank=True,
                help_text="HBhistBB (als URL)",
                max_length=400,
                null=True,
                verbose_name="HBhistBB",
            ),
        ),
        migrations.AddField(
            model_name="bibliothek",
            name="hmml_img",
            field=models.IntegerField(
                blank=True, help_text="HMML_img", null=True, verbose_name="HMML_img"
            ),
        ),
        migrations.AddField(
            model_name="bibliothek",
            name="hmml_msid",
            field=models.IntegerField(
                blank=True, help_text="HMML_MSID", null=True, verbose_name="HMML_MSID"
            ),
        ),
        migrations.AddField(
            model_name="bibliothek",
            name="homepage",
            field=models.URLField(
                blank=True,
                help_text="Link zur Website",
                max_length=400,
                null=True,
                verbose_name="Website",
            ),
        ),
        migrations.AddField(
            model_name="bibliothek",
            name="long_lat",
            field=models.CharField(
                blank=True,
                help_text="(Long,Lat)",
                max_length=250,
                verbose_name="Koordinaten",
            ),
        ),
    ]
