# Generated by Django 3.1.1 on 2020-10-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0008_auto_20201023_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verfasser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('name', models.CharField(blank=True, help_text='Name', max_length=250, verbose_name='Name')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
            ],
            options={
                'verbose_name': 'Verfasser',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MsDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=300, verbose_name='Legacy ID')),
                ('legacy_pk', models.IntegerField(blank=True, help_text='Primärschlüssel Alt', null=True, verbose_name='Primärschlüssel Alt')),
                ('bibliography', models.TextField(blank=True, help_text='Bibliographie', null=True, verbose_name='Bibliographie')),
                ('phys_desc', models.TextField(blank=True, help_text='phys_desc', null=True, verbose_name='phys_desc')),
                ('content', models.TextField(blank=True, help_text='content', null=True, verbose_name='content')),
                ('created', models.DateField(blank=True, help_text='Erstellungsdatum', null=True, verbose_name='Erstellungsdatum')),
                ('orig_data_csv', models.TextField(blank=True, null=True, verbose_name='The original data')),
                ('manuscript', models.ForeignKey(blank=True, help_text='Manuscript', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_msdesc_manuscript_manuscript', to='archiv.manuscript', verbose_name='Manuscript')),
                ('verfasser', models.ForeignKey(blank=True, help_text='Verfasser*In', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvn_msdesc_verfasser_verfasser', to='archiv.verfasser', verbose_name='Verfasser*In')),
            ],
            options={
                'verbose_name': 'Manuscript Description',
                'ordering': ['legacy_pk'],
            },
        ),
    ]
