# Generated by Django 5.1.1 on 2024-09-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0009_alter_bibliothek_long_lat"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Einband",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "lokalisierung",
                    models.CharField(
                        blank=True,
                        help_text="Lokalisierung",
                        max_length=250,
                        verbose_name="Lokalisierung",
                    ),
                ),
                (
                    "werkstatt",
                    models.CharField(
                        blank=True,
                        help_text="Werkstatt",
                        max_length=250,
                        verbose_name="Werkstatt",
                    ),
                ),
                (
                    "fragment",
                    models.IntegerField(
                        blank=True,
                        help_text="fragment",
                        null=True,
                        verbose_name="fragment",
                    ),
                ),
                (
                    "datierung",
                    models.CharField(
                        blank=True,
                        help_text="Datierung",
                        max_length=250,
                        verbose_name="Datierung",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="ISO-Date nicht vor (JJJJ-MM-TT)",
                        null=True,
                        verbose_name="Datierung (nicht vor)",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="ISO-Date nicht nach (JJJJ-MM-TT)",
                        null=True,
                        verbose_name="Datierung (nicht nach)",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Anmerkungen",
                        null=True,
                        verbose_name="Anmerkungen",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manuscript",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_einband_manuscript_manuscript",
                        to="archiv.manuscript",
                        verbose_name="Manuscript",
                    ),
                ),
                (
                    "schmuck",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schmuck",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_einband_schmuck_skosconcept",
                        to="vocabs.skosconcept",
                        verbose_name="Schmuck",
                    ),
                ),
                (
                    "stil",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stil",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_einband_stil_skosconcept",
                        to="vocabs.skosconcept",
                        verbose_name="Stil",
                    ),
                ),
                (
                    "verfasser",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verfasser*In",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_einband_verfasser_verfasser",
                        to="archiv.verfasser",
                        verbose_name="Verfasser*In",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einband",
                "ordering": ["legacy_pk"],
            },
        ),
    ]
