# Generated by Django 5.1.1 on 2024-09-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0010_einband"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "schr_hohe",
                    models.CharField(
                        blank=True,
                        help_text="Höhe der Schrift",
                        max_length=250,
                        verbose_name="Schrifthöhe",
                    ),
                ),
                (
                    "schr_breite",
                    models.CharField(
                        blank=True,
                        help_text="Breite der Schrift",
                        max_length=250,
                        verbose_name="Schriftbreite",
                    ),
                ),
                (
                    "spaltenzahl",
                    models.CharField(
                        blank=True,
                        help_text="Spaltenzahl",
                        max_length=250,
                        verbose_name="Spaltenzahl",
                    ),
                ),
                (
                    "zeilenzahl",
                    models.CharField(
                        blank=True,
                        help_text="Zeilenanzahl",
                        max_length=250,
                        verbose_name="Zeilenanzahl",
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        blank=True,
                        help_text="Folio-Folio",
                        max_length=250,
                        verbose_name="Positionierung",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position",
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "marginalien",
                    models.IntegerField(
                        blank=True,
                        help_text="Marginalien",
                        null=True,
                        verbose_name="Marginalien",
                    ),
                ),
                (
                    "glossen",
                    models.IntegerField(
                        blank=True,
                        help_text="Glossen",
                        null=True,
                        verbose_name="Glossen",
                    ),
                ),
                (
                    "geheimschrift",
                    models.IntegerField(
                        blank=True,
                        help_text="Geheimschrift",
                        null=True,
                        verbose_name="Geheimschrift",
                    ),
                ),
                (
                    "notation",
                    models.IntegerField(
                        blank=True,
                        help_text="Notation",
                        null=True,
                        verbose_name="Notation",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Anmerkungen",
                        null=True,
                        verbose_name="Anmerkungen",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manuscript",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_schrift_manuscript_manuscript",
                        to="archiv.manuscript",
                        verbose_name="Manuscript",
                    ),
                ),
                (
                    "mspart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teil einer Handschrift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_schrift_mspart_mspart",
                        to="archiv.mspart",
                        verbose_name="MS Part",
                    ),
                ),
                (
                    "schmuck",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schmuck",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_schrift_schmuck_skosconcept",
                        to="vocabs.skosconcept",
                        verbose_name="Schmuck",
                    ),
                ),
                (
                    "schriftart",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schriftart",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_schrift_schriftart_skosconcept",
                        to="vocabs.skosconcept",
                        verbose_name="Schriftart",
                    ),
                ),
                (
                    "verfasser",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verfasser*In",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_schrift_verfasser_verfasser",
                        to="archiv.verfasser",
                        verbose_name="Verfasser*In",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schrift",
                "ordering": ["legacy_pk"],
            },
        ),
    ]
