# Generated by Django 5.1.1 on 2024-09-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0011_schrift"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mspart",
            name="aus_remarks",
            field=models.TextField(
                blank=True,
                help_text="Anmerkungen zur Ausstattung",
                null=True,
                verbose_name="Anmerkungen zur Ausstattung",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="ausstattung",
            field=models.ForeignKey(
                blank=True,
                help_text="Ausstattung",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_ausstattung_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Ausstattung",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="lagen",
            field=models.TextField(
                blank=True, help_text="Lagen", null=True, verbose_name="Lagen"
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="Teil Code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_material_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Teil Code",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="oc",
            field=models.ForeignKey(
                blank=True,
                help_text="OC",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_oc_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="OC",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="part",
            field=models.CharField(
                blank=True, help_text="Teil", max_length=250, verbose_name="Teil"
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="part_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Teil Code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_part_code_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Teil Code",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="part_sort",
            field=models.CharField(
                blank=True,
                help_text="Teil (Sortierung)",
                max_length=250,
                verbose_name="Teil (Sortierung)",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Anmerkungen",
                null=True,
                verbose_name="Anmerkungen",
            ),
        ),
        migrations.AddField(
            model_name="mspart",
            name="verfasser",
            field=models.ForeignKey(
                blank=True,
                help_text="Verfasser*In",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_verfasser_verfasser",
                to="archiv.verfasser",
                verbose_name="Verfasser*In",
            ),
        ),
    ]
