# Generated by Django 5.1.1 on 2024-09-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0012_mspart_aus_remarks_mspart_ausstattung_mspart_lagen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="Dateiname",
                        max_length=250,
                        verbose_name="Dateiname",
                    ),
                ),
                (
                    "extpath",
                    models.CharField(
                        blank=True,
                        help_text="Link zu externer Resource",
                        max_length=400,
                        verbose_name="Link zu externer Resource",
                    ),
                ),
                (
                    "fol",
                    models.CharField(
                        blank=True,
                        help_text="Folio",
                        max_length=250,
                        verbose_name="Folio",
                    ),
                ),
                (
                    "fol_sort",
                    models.CharField(
                        blank=True,
                        help_text="Folio (Sortierung)",
                        max_length=250,
                        verbose_name="Folio (Sortierung)",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Beschreibung des Bildes",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Anmerkungen",
                        null=True,
                        verbose_name="Anmerkungen",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manuscript",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_msimage_manuscript_manuscript",
                        to="archiv.manuscript",
                        verbose_name="Manuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "MsImage",
                "ordering": ["manuscript", "fol_sort"],
            },
        ),
    ]
