# Generated by Django 5.1.1 on 2024-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0013_msimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msimage",
            options={
                "ordering": ["manuscript", "fol_sort"],
                "verbose_name": "Bilddatei",
            },
        ),
        migrations.AlterModelOptions(
            name="mspart",
            options={
                "ordering": ["part_of_manuscript", "part_sort"],
                "verbose_name": "MsPart",
            },
        ),
        migrations.AddField(
            model_name="einband",
            name="orig_data_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="The original data"
            ),
        ),
        migrations.AddField(
            model_name="msimage",
            name="orig_data_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="The original data"
            ),
        ),
        migrations.AddField(
            model_name="schrift",
            name="orig_data_csv",
            field=models.TextField(
                blank=True, null=True, verbose_name="The original data"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="jahrhundert",
            field=models.CharField(
                blank=True,
                help_text="Jahrhundert (in standardisierter Schreibweise)",
                max_length=250,
                null=True,
                verbose_name="Jahrhundert",
            ),
        ),
    ]
