# Generated by Django 5.1.1 on 2024-09-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0014_alter_msimage_options_alter_mspart_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_gnd",
                    models.CharField(
                        blank=True,
                        help_text="Name (GND)",
                        max_length=250,
                        verbose_name="Name (GND)",
                    ),
                ),
                (
                    "gnd_id",
                    models.CharField(
                        blank=True,
                        help_text="GND-ID",
                        max_length=250,
                        verbose_name="GND-ID",
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        blank=True, help_text="Typ", max_length=250, verbose_name="Typ"
                    ),
                ),
                (
                    "funktion",
                    models.CharField(
                        blank=True,
                        help_text="Funktion",
                        max_length=250,
                        verbose_name="Funktion",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Anmerkungen",
                        null=True,
                        verbose_name="Anmerkungen",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "ort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ort",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_person_ort_place",
                        to="archiv.place",
                        verbose_name="Ort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "ordering": ["name", "id"],
            },
        ),
    ]
