# Generated by Django 5.1.1 on 2024-09-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0015_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsProv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "prov_signatur",
                    models.CharField(
                        blank=True,
                        help_text="Proveninez Signatur",
                        max_length=250,
                        verbose_name="Proveninez Signatur",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        help_text="date",
                        max_length=250,
                        verbose_name="date",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="ISO-Date nicht vor (JJJJ-MM-TT)",
                        null=True,
                        verbose_name="Datierung (nicht vor)",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="ISO-Date nicht nach (JJJJ-MM-TT)",
                        null=True,
                        verbose_name="Datierung (nicht nach)",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Anmerkungen",
                        null=True,
                        verbose_name="Anmerkungen",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manuscript",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_msprov_manuscript_manuscript",
                        to="archiv.manuscript",
                        verbose_name="Manuscript",
                    ),
                ),
                (
                    "previous_owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vorbesitzer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_msprov_person_skosconcept",
                        to="archiv.person",
                        verbose_name="Vorbesitzer",
                    ),
                ),
                (
                    "prov_lib",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provenienz Bibliothek",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_msprov_prov_lib_bibliothek",
                        to="archiv.bibliothek",
                        verbose_name="Provenienz Bibliothek",
                    ),
                ),
                (
                    "verfasser",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verfasser*In",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_msprov_verfasser_verfasser",
                        to="archiv.verfasser",
                        verbose_name="Verfasser*In",
                    ),
                ),
            ],
            options={
                "verbose_name": "MsProv",
                "ordering": ["legacy_pk"],
            },
        ),
    ]
