# Generated by Django 5.1.1 on 2024-09-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0016_msprov"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msprov",
            options={
                "ordering": ["legacy_pk"],
                "verbose_name": "Provenienz der Handschrift",
            },
        ),
        migrations.AddField(
            model_name="msprov",
            name="prov_manuscript",
            field=models.ForeignKey(
                blank=True,
                help_text="Provenienz Handschrift",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_msprov_prov_manuscript_manuscript",
                to="archiv.manuscript",
                verbose_name="Provenienz Handschrift",
            ),
        ),
    ]
