# Generated by Django 5.1.1 on 2024-09-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0017_alter_msprov_options_msprov_prov_manuscript"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="werkinstanz",
            options={
                "ordering": ["fol_sort", "legacy_pk"],
                "verbose_name": "Instanz eines Werkes",
            },
        ),
        migrations.RemoveField(
            model_name="autor",
            name="bibliography",
        ),
        migrations.AddField(
            model_name="werkinstanz",
            name="bibliography",
            field=models.TextField(
                blank=True,
                help_text="Bibliographie",
                null=True,
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AddField(
            model_name="werkinstanz",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Anmerkungen zur Ausstattung",
                null=True,
                verbose_name="Anmerkungen",
            ),
        ),
        migrations.AddField(
            model_name="werkinstanz",
            name="source",
            field=models.TextField(
                blank=True,
                help_text="Bibliographie",
                null=True,
                verbose_name="Bibliographie",
            ),
        ),
        migrations.AddField(
            model_name="werkinstanz",
            name="verfasser",
            field=models.ForeignKey(
                blank=True,
                help_text="Verfasser*In",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_werkinstanz_verfasser_verfasser",
                to="archiv.verfasser",
                verbose_name="Verfasser*In",
            ),
        ),
        migrations.AlterField(
            model_name="msprov",
            name="previous_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Vorbesitzer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_msprov_previous_owner_person",
                to="archiv.person",
                verbose_name="Vorbesitzer",
            ),
        ),
    ]
