# Generated by Django 5.1.1 on 2024-10-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0018_alter_werkinstanz_options_remove_autor_bibliography_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="data_source",
            field=models.CharField(
                blank=True, help_text="Quelle", max_length=250, verbose_name="Quelle"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="date_zusatz",
            field=models.CharField(
                blank=True,
                help_text="Ergänzung zur Datierung",
                max_length=250,
                verbose_name="Datierungsanmerkung",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="gesbeschreibung",
            field=models.TextField(
                blank=True,
                help_text="Beschreibung der Gestalt",
                null=True,
                verbose_name="Gestaltsbeschreibung",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="verfasser",
            field=models.ForeignKey(
                blank=True,
                help_text="Verfasser*In",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_manuscript_verfasser_verfasser",
                to="archiv.verfasser",
                verbose_name="Verfasser*In",
            ),
        ),
    ]
