# Generated by Django 5.1.1 on 2024-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0019_manuscript_data_source_manuscript_date_zusatz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliothek",
            name="literatur",
            field=models.ManyToManyField(
                blank=True,
                help_text="Kataloge",
                related_name="rvn_bibliothek_literatur_literatur",
                to="archiv.literatur",
                verbose_name="Katologe",
            ),
        ),
    ]
