# Generated by Django 5.1.1 on 2024-10-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0020_bibliothek_literatur"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="literatur",
            name="cit_short",
            field=models.CharField(
                blank=True,
                help_text="Für die Auflösung von Kurzzitaten benötigt",
                max_length=250,
                verbose_name="citshort",
            ),
        ),
        migrations.AlterField(
            model_name="mspart",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="Material",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_mspart_material_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Material",
            ),
        ),
    ]
