# Generated by Django 5.1.1 on 2024-10-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0021_literatur_cit_short_alter_mspart_material"),
        ("vocabs", "0002_alter_metadata_id_alter_metadata_indentifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="format",
            field=models.ForeignKey(
                blank=True,
                help_text="Format",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rvn_manuscript_format_skosconcept",
                to="vocabs.skosconcept",
                verbose_name="Format",
            ),
        ),
    ]
